### ISSUE TITLE
Does not work for Jabber chatrooms (MUC)

### ISSUE THREAD

**Issue by teranex** [xintron/irssi-pushover#4]
First of all thanks for the nice plugin!

I found there is a small issue with the plugin: when using the irssi-plugin-xmpp to connect to a Jabber network, the script works for private messages, but it does not work for mentions in a chatroom (MUC). The reason for this is that `$server->{nick}` returns the JabberID (foo@jabber.com), while the nick in the room is in most cases different, causing `if ($data =~ /$safeNick/i) {` to always be false.
I was able to hack a working version by looking at another script. (I really mean 'hack' as I don't know any Perl). This is what I came up with:

``` perl
sub msg_print_text {
    my ($dest, $text, $stripped) = @_;
    my $server = $dest->{server};
    my $target = $dest->{target};

    return if (!$server || !($dest->{level} & MSGLEVEL_HILIGHT));

    if(check_ignore_channels($target)) {
        return;
    }

    if(check_away($server)) {
        return;
    }

    debug('Got nick highlight');
    $stripped =~ s/^\s+|\s+$//g;
    send_push($target, $stripped);
}

Irssi::signal_add_last('print text', 'msg_print_text');
```

**Comment by xintron** [comment]
I don't run irssi myself anymore and never used the xmpp-plugin (I use bitlbee
for that).

This is a bit of a corner case and I currently don't have the time to set up
irssi + plugins to test this out and patch it for the moment.

It would be great if you could send a patch/pull request which would make it a
bit easier to quickly test it out and if it works just merge the fix.

**Comment by teranex** [comment]
Created the pull request: https://github.com/xintron/irssi-pushover/pull/5

I have been using this for the past week now and it seems to work without problems, but please keep in mind that I'm not a Perl programmer :)

**Comment by aanari** [comment]
This is simple, clean, and it works!  @teranex++

**Comment by xintron** [comment]
This has been merged based on the feedback from you guys (saying that it works).
